Create table Movies
(
	movie_id int identity(1,1) not null primary key, --renamed to id
	name varchar(5000) not null,
	genre varchar(5000) not null,
	numberOfDiscs int not null,

);


Create table TvShows
(
	show_id int identity(1,1) not null, -- renamed to id
	name varchar(5000) not null,
	genre varchar(5000) not null,
	numberOfDiscs int not null,
	hasMovie bit not null

	constraint pk_show_id Primary key (show_id)

);

Alter Table TvShows Add FOREIGN KEY (id) REFERENCES Movies(id);


Alter Table TvShows Add numberOfSeasons int;



Insert into Movies (name, genre, numberOfDiscs)
Values ('Harry Potter and the Sorcerers Stone', 'Adventure', 2),
('Harry Potter and the Chamber of Secrets', 'Adventure', 2),
('Harry Potter and the Prisoner of Azkaban', 'Adventure', 2),
('Harry Potter and the Goblet of Fire', 'Adventure', 2),
('Harry Potter and the Order of the Phoenix', 'Adventure', 1),
('Harry Potter and Half-Blood Prince', 'Adventure', 1),
('Harry Potter and Deathly Hallows Part 1', 'Adventure', 2),
('Harry Potter and Deathly Hallows Part 2', 'Adventure', 2);
Insert into Movies (name, genre, numberOfDiscs)
Values ('Beverly Hills Cop', 'Comedy', 1),
('Beverly Hills Cop II', 'Comedy', 1),
('Beverly Hills Cop III', 'Comedy', 1),
('The Blind Side', 'Drama(Based on a true story)', 1),
('Bend it Like Beckham', 'Drama', 1),
('Bedtime Stories', 'Comedy', 2),
('Disturbia', 'Suspense', 1),
('The Mighty Ducks', 'Comedy', 1),
('D2: The Mighty Ducks', 'Comedy', 1),
('D3: The Mighty Ducks', 'Comedy', 1),
('Good Luck Chuck', 'Comedy', 1),
('Herbie: Fully Loaded', 'Comedy', 1),
('Hitch', 'Romantic Comedy(Chick Flick)', 1),
('Happy Gilmore', 'Comedy', 1),
('It Could Happen to You', 'Romantic Comedy(Chick Flick)', 1),
('Journey to the Center of the Earth', 'Adventure', 1),
('Knocked Up', 'Comedy', 1),
('License to Wed', 'Romantic Comedy(Chick Flick)', 1);
Insert into Movies (name, genre, numberOfDiscs)
Values ('Supergirl', 'Action', 1),
('Superman', 'Action', 1),
('Superman II', 'Action', 1),
('Superman III', 'Action', 1),
('Superman IV: The Quest for Peace', 'Action', 1),
('Superman Returns', 'Action', 1),
('The Simpsons Movie', 'Animated Comedy', 1),
('Teenage Mutant Ninja Turtles', 'Action', 1),
('Teenage Mutant Ninja Turtles II', 'Action', 1),
('Teenage Mutant Ninja Turtles III', 'Action', 1),
('TMNT', 'Action', 1),
('The Wedding Singer', 'Comedy', 1),
('Monsters, Inc.', 'Pixar Comedy', 2),
('Enchanted', 'Romantic Comedy(Chick Flick)', 1),
('Yes Man', 'Comedy', 1),
('Under Siege', 'Action', 1),
('Under Siege 2: Dark Territory', 'Action', 1),
('Space Jam', 'Animated Comedy', 2),
('Robin Hood: Prince of Thieves', 'Adventure', 1);
Insert into Movies (name, genre, numberOfDiscs)
Values('Glory Road', 'Drama(Based on a True Story)', 1),
('Facing the Giants', 'Drama', 1),
('Catch Me if You Can', 'Drama', 2),
('Fever Pitch', 'Comedy', 1),
('Cars', 'Pixar Comedy', 1),
('Billy Madison', 'Comedy', 1),
('Blue Streak', 'Comedy', 1),
('Coach Carter', 'Drama(Based on a True Story)', 1),
('Troy', 'Drama', 2),
('We Are Marshall', 'Drama(Based on a True Story)', 1),
('Stealth', 'Action', 1),
('Stranger than Fiction', 'Comedy', 1),
('The Express: The Ernie Davis Story', 'Drama(Based on a True Story)', 1),
('Hancock', 'Action', 1);
Insert into Movies (name, genre, numberOfDiscs)
Values ('Inspector Gadget', 'Comedy', 1),
('Inspector Gadget 2', 'Comedy', 1),
('Mr. Deeds', 'Comedy', 1),
('Major League', 'Comedy', 1),
('Major League II', 'Comedy', 1),
('Major League: Back to the Minors', 'Comedy', 1),
('The Incredibles', 'Pixar Comedy', 2),
('Garfield: The Movie', 'Comedy', 1),
('Garfield: A Tail of Two Kitties', 'Comedy', 1),
('Click', 'Comedy', 1),
('Eurotrip', 'Comedy', 1),
('The Karate Kid', 'Action', 1),
('The House Bunny', 'Comedy', 1),
('The Waterboy', 'Comedy', 1),
('The Tuxedo', 'Comedy', 1),
('Shes The Man', 'Comedy', 1),
('The Bucket List', 'Comedy', 1),
('Bloodsport', 'Action', 1),
('Timecop', 'Action', 1);
Insert into Movies (name, genre, numberOfDiscs)
Values ('Transformers', 'Action', 1),
('Transformers: Revenge of the Fallen', 'Action', 2),
('Transformers: Dark of the Moon', 'Action', 2),
('Harold & Kumar Go To White Castle', 'Comedy', 1),
('Harold & Kumar Escape From Guantanamo Bay', 'Comedy', 1),
('Ice', 'Action', 1),
('A Rage in Harlem', 'Action', 1),
('The Glass Shield', 'Action', 1),
('Malevolent', 'Action', 1),
('License to Kill', 'Action', 1),
('Road Ends', 'Action', 1),
('In Too Deep', 'Action', 1),
('Cry the Beloved Country', 'Action', 1),
('The Pacifier', 'Comedy', 1),
('Slumdog Millionaire', 'Drama', 1),
('Speed Racer', 'Action', 1),
('Get Smart', 'Comedy', 1),
('Accepted', 'Comedy', 1),
('October Sky', 'Drama(Based on a True Story)', 1),
('Raising Helen', 'Romantic Comedy(Chick Flick)', 1),
('Race to Witch Mountain', 'Adventure', 1),
('Philadelphia', 'Drama', 1),
('Paul Blart Mall Cop', 'Comedy', 1),
('Monty Python and the Holy Grail', 'Comedy', 1),
('Remember the Titans', 'Drama(Based on a True Story)', 1),
('Love Wrecked', 'Comedy', 1),
('Night at the Museum', 'Romantic Comedy(Chick Flick)', 1),
('Night at the Museum: Battle of the Smithsonian', 'Comedy', 1),
('Convict 762', 'Action', 1),
('Fortress', 'Action', 1),
('Total Recall 2070: Machine Dreams', 'Action', 1),
('Cypher', 'Action', 1),
('Trancers I', 'Action', 1),
('Equilibrium', 'Action', 1),
('Impostor', 'Action', 1),
('The Prophecy', 'Action', 1),
('The Flintstones', 'Comedy', 1),
('The Game Plan', 'Comedy', 1),
('The Heartbreak Kid', 'Comedy', 1),
('Sweet Home Alabama', 'Romantic Comedy(Chick Flick)', 1),
('Sydney White', 'Romantic Comedy(Chick Flick)', 1),
('Van Wilder', 'Comedy', 2),
('Van Wilder: The Rise of Taj', 'Comedy', 1),
('Live Free or Die Hard', 'Action', 1),
('Looney Tunes: Back in Action', 'Comedy', 1),
('A Time to Kill', 'Drama', 1),
('Rookie of the Year', 'Comedy', 1),
('Alvin and the Chipmunks', 'Comedy', 1),
('Alvin and the Chipmunks: The Squeakquel', 'Comedy', 1),
('Alvin and the Chipmunks: Chipwrecked', 'Comedy', 1),
('Austin Powers', 'Comedy', 1),
('Austin Powers: The Spy Who Shagged Me', 'Comedy', 1),
('Austin Powers: Goldmember', 'Comedy', 1);
Insert into Movies (name, genre, numberOfDiscs)
Values ('X-men', 'Action', 1),
('X-men 2: X-men United', 'Action', 2),
('X-men 3: The Last Stand', 'Action', 1),
('The Mask of Zorro', 'Action', 1),
('The Legend of Zorro', 'Action', 2),
('The Terminal', 'Romantic Comedy (Chick Flick)', 1),
('Timeline', 'Action', 1),
('Batman', 'Action', 1),
('Batman Returns', 'Action', 1),
('Batman Forever', 'Action', 1),
('Batman & Robin', 'Action', 1),
('Shrek', 'Comedy', 1),
('Shrek 2', 'Comedy', 1),
('Shrek The Third', 'Comedy', 2),
('Shrek Forever After: The Final Chapter', 'Comedy', 1);
Insert into Movies (name, genre, numberOfDiscs)
Values ('Avengers', 'Action', 1),
('Armageddon', 'Action', 1),
('Bicentennial Man', 'Drama', 1),
('A Beautiful Mind', 'Drama(Based on a True Story)', 2),
('Bewitched', 'Comedy', 1),
('Broken Arrow', 'Action', 1),
('Bruce Almighty', 'Comedy', 1),
('Evan Almighty', 'Comedy', 1),
('Captain America: The First Avenger', 'Action', 1),
('Cast Away', 'Drama', 1),
('Deep Impact', 'Drama', 1),
('Mrs. Doubtfire', 'Comedy', 2),
('The DaVinci Code', 'Drama', 2),
('Double Jeopardy', 'Action', 1),
('Enemy of the State', 'Action', 1),
('Face/Off', 'Action', 1),
('Independence Day', 'Action', 1),
('The Fugitive', 'Action', 1),
('US Marshals', 'Action', 1),
('Batman Begins', 'Action', 1),
('Batman: The Dark Knight', 'Action', 2),
('Lethal Weapon 4', 'Action', 1),
('Outbreak', 'Drama', 1),
('Spaceballs', 'Comedy', 1),
('The Girl Next Door', 'Romantic Comedy (Chick Flick)', 1),
('Maverick', 'Comedy', 1),
('Wild Wild West', 'Comedy', 1);
Insert into Movies (name, genre, numberOfDiscs)
Values ('Star Wars Episode I: The Phantom Menace', 'Action', 2),
('Star Wars Episode II: Attack of the Clones', 'Action', 2),
('Star Wars Episode III: Revenge of the Sith', 'Action', 2),
('Star Wars Episode IV: A New Hope', 'Action', 2),
('Stars Wars Episode V: The Empire Strikes Back', 'Action', 2),
('Star Wars Episode VI; Return of the Jedi', 'Action', 2),
('Sister Act', 'Comedy', 1),
('Sister Act 2: Back in the Habit', 'Comedy', 1),
('Spiderman', 'Action', 2),
('Spiderman 2', 'Action', 2),
('Spiderman 3', 'Action', 1),
('Fantastic Four', 'Action', 1),
('Fantastic Four: Rise of the Silver Surfer', 'Action', 1),
('National Treasure', 'Action', 1),
('National Treasure 2: Book of Secrets', 'Action', 1),
('The Mummy', 'Action', 2),
('The Mummy Returns', 'Action', 1),
('The Mummy: Tomb of the Dragon Emperor', 'Action', 2),
('The Mask', 'Comedy', 1),
('Liar Liar', 'Comedy', 1),
('I Am Legend', 'Drama', 2),
('James Bond: Licence to Kill', 'Action', 1),
('Last Action Hero', 'Action', 1),
('Looks Whos Talking Now!', 'Comedy', 1),
('Jumanji', 'Comedy', 1),
('Forrest Gump', 'Drama', 2),
('Gandhi', 'Drama(Based on a True Story)', 2);
Insert into Movies (name, genre, numberOfDiscs)
Values ('Robocop', 'Action', 1),
('The Replacements', 'Comedy', 1),
('The Rookie', 'Drama(Based on a True Story)', 1),
('Wild Hogs', 'Comedy', 1),
('Tooth Fairy', 'Comedy', 1),
('The Shawshank Redemption', 'Drama', 1),
('True Lies', 'Action', 1),
('Speed', 'Action', 1),
('Air Force One', 'Action', 1),
('Rush Hour', 'Comedy', 1),
('Rush Hour 2', 'Comedy', 1),
('Rush Hour 3', 'Comedy', 1),
('The Terminator', 'Action', 1),
('Terminator 2: Judgment Day', 'Action', 2),
('Terminator 3: Rise of the Machines', 'Action', 2),
('The Producers', 'Musical', 1),
('No Reservations', 'Romantic Comedy', 1),
('Little Big League', 'Comedy', 1),
('Little Giants', 'Comedy', 1),
('Star Trek Generations', 'Action', 1),
('Star Trek First Contact', 'Action', 1),
('Star Trek Insurrection', 'Action', 1),
('Star Trek Nemesis', 'Action', 1),
('Grown Ups', 'Comedy', 1),
('G.I. Joe: The Rise of Cobra', 'Action', 2),
('Back to the Future', 'Action', 1),
('Back to the Future II', 'Action', 1),
('Back to the Future III', 'Action', 1),
('Home Alone', 'Comedy', 1),
('Home Alone 2', 'Comedy', 1),
('Home Alone 3', 'Comedy', 1),
('Iron Man', 'Action', 2),
('Iron Man 2', 'Action', 2),
('Legally Blonde', 'Romantic Comedy(Chick Flick)', 1),
('Legally Blonde 2: Red, White, & Blonde', 'Romantic Comedy (Chick Flick)', 1),
('Men In Black(MIB)', 'Comedy', 2),
('Jurassic Park', 'Action', 1),
('American Pie', 'Comedy', 2),
('American Pie 2', 'Comedy', 1),
('American Wedding', 'Comedy', 1),
('Indiana Jones and the Kingdom of the Crystal Skull', 'Action', 1); 

Insert into TvShows(name, genre, numberOfDiscs, hasMovie, numberOfSeasons)
Values ('MLB Bloopers', 'Sports', 1, 0, 1);

Insert into TvShows(name, genre, numberOfDiscs, hasMovie, numberOfSeasons)
Values ('Knight Rider 1982-1986', 'Action', 24, 1, 4),
('Knight Rider 2008', 'Action', 4, 1, 1),
('Pee-wees Playhouse', 'Comedy', 11, 1, 5),
('House', 'Drama', 36,0,8);


 